import { Town, Shop, Product, Job } from "./types";

export const TOWNS: Town[] = [
  { id: "kitengela", name: "Kitengela", latitude: -1.4753, longitude: 36.961, shop_count: 5 },
  { id: "kajiado-town", name: "Kajiado Town", latitude: -1.8522, longitude: 36.796, shop_count: 0 },
  { id: "rongai", name: "Rongai", latitude: -1.3964, longitude: 36.4535, shop_count: 3 },
  { id: "ngong", name: "Ngong", latitude: -1.3659, longitude: 36.6589, shop_count: 0 },
  { id: "namanga", name: "Namanga", latitude: -2.5536, longitude: 36.7962, shop_count: 0 },
];

export const SHOPS: Shop[] = [
  {
    id: "kit-1", town_id: "kitengela", name: "Savanna Supermarket",
    tagline: "Fresh Goods, Fair Prices — Every Day",
    description: "Your one-stop shop for fresh groceries, household goods, and local produce in the heart of Kitengela. We stock everything from fresh farm produce to packaged goods and household essentials.",
    category: "Grocery", color: "#16a34a",
    image_url: "https://images.unsplash.com/photo-1542838292-a9d4e3d0c4e3?auto=format&w=800&q=75",
    is_premium: true, phone: "+254 712 345 678", whatsapp: "+254712345678", hours: "Mon–Sat 7am–9pm, Sun 8am–7pm",
  },
  {
    id: "kit-2", town_id: "kitengela", name: "Maasai Craft Gallery",
    tagline: "Where Heritage Meets Artistry",
    description: "Authentic handcrafted beadwork, leather goods, and traditional Maasai jewellery sourced directly from local artisans. Each piece tells a story of Kajiado's rich cultural heritage.",
    category: "Crafts & Art", color: "#C36F48",
    image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&w=800&q=75",
    is_premium: true, phone: "+254 723 456 789", whatsapp: "+254723456789", hours: "Daily 9am–6pm",
  },
  {
    id: "kit-3", town_id: "kitengela", name: "Plains Hardware & Steel",
    tagline: "Built for Builders Across Kajiado",
    description: "Construction materials, roofing sheets, plumbing supplies, and power tools for builders across Kajiado County. Trusted by contractors and homeowners alike for over a decade.",
    category: "Hardware", color: "#374151",
    image_url: "https://images.unsplash.com/photo-1504328345596-84a2834cce01?auto=format&w=800&q=75",
    is_premium: false, phone: "+254 734 567 890", hours: "Mon–Sat 7:30am–6pm",
  },
  {
    id: "kit-4", town_id: "kitengela", name: "Acacia Mobile Hub",
    tagline: "Stay Connected. Stay Ahead.",
    description: "Mobile phones, accessories, repairs, and mobile money services. Authorised dealer for major Kenyan networks. Expert technicians handle all repairs on-site within the day.",
    category: "Electronics", color: "#2563eb",
    image_url: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&w=800&q=75",
    is_premium: false, phone: "+254 745 678 901", whatsapp: "+254745678901", hours: "Mon–Sat 8am–8pm, Sun 10am–6pm",
  },
  {
    id: "kit-5", town_id: "kitengela", name: "The Ochre Kitchen",
    tagline: "Taste the Heart of Kajiado",
    description: "A warm family restaurant serving Nyama Choma, ugali, and seasonal local dishes. Known for the best pilau in town. Our recipes have been passed down through generations of Kajiado cooks.",
    category: "Restaurant", color: "#ea580c",
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&w=800&q=75",
    is_premium: true, phone: "+254 756 789 012", whatsapp: "+254756789012", hours: "Daily 11am–10pm",
  },
  {
    id: "ron-1", town_id: "rongai", name: "Rongai Fresh Market",
    tagline: "Farm Fresh, Delivered Daily",
    description: "Daily fresh vegetables, fruits, and farm produce delivered straight from smallholder farms in the surrounding area. We work directly with over 30 local farmers to guarantee freshness and fair prices.",
    category: "Grocery", color: "#15803d",
    image_url: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&w=800&q=75",
    is_premium: false, phone: "+254 767 890 123", hours: "Daily 6am–7pm",
  },
  {
    id: "ron-2", town_id: "rongai", name: "Oloolua Pharmacy",
    tagline: "Your Health, Our Priority",
    description: "Licensed pharmaceutical store offering prescription medicines, wellness products, and free blood pressure checks. Our qualified pharmacists provide personalised health advice Monday to Saturday.",
    category: "Health & Pharmacy", color: "#0d9488",
    image_url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&w=800&q=75",
    is_premium: true, phone: "+254 778 901 234", whatsapp: "+254778901234", hours: "Mon–Sat 8am–8pm, Sun 9am–5pm",
  },
  {
    id: "ron-3", town_id: "rongai", name: "Shepherd's Inn & Lounge",
    tagline: "Rest Well in the Heart of Rongai",
    description: "Comfortable accommodation, conference facilities, and a full-service bar overlooking the Ngong Hills. Ideal for business travellers and weekend retreats with reliable Wi-Fi and full catering.",
    category: "Hospitality", color: "#7c3aed",
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&w=800&q=75",
    is_premium: true, phone: "+254 789 012 345", whatsapp: "+254789012345", hours: "Open 24 hours",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p-1", name: "Unga (Maize Flour) 2kg",
    description: "Premium white maize flour. Stone-ground, bulk sourced from certified millers. Perfect for ugali and baking.",
    price: 190, unit: "2 kg bag", category: "Dry Goods", in_stock: true, badge: "Best Seller",
    image_url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-2", name: "Cooking Oil 5L",
    description: "Pure sunflower cooking oil. Sourced directly from processors — light, healthy, and ideal for deep frying.",
    price: 1050, unit: "5 litre jerrican", category: "Oils & Fats", in_stock: true, badge: "Wholesale Price",
    image_url: "https://images.unsplash.com/photo-1474979479409-9a29bd5a2c5b?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-3", name: "Sugar 2kg",
    description: "White refined sugar. Directly sourced from a leading Kenyan manufacturer. Ideal for tea, cooking, and resale.",
    price: 280, unit: "2 kg bag", category: "Dry Goods", in_stock: true,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-4", name: "Bar Soap (Packed 6s)",
    description: "Multi-purpose laundry and bath soap bars. Bulk-packed directly from manufacturer. Great for household and resale.",
    price: 360, unit: "pack of 6 bars", category: "Household", in_stock: true, badge: "Bulk Deal",
    image_url: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-5", name: "Maasai Beaded Bracelet",
    description: "Handwoven traditional beaded bracelet. Sourced from Maasai artisans in Kajiado. Each piece is unique.",
    price: 450, unit: "per piece", category: "Crafts", in_stock: true, badge: "Authentic",
    image_url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-6", name: "Tomatoes (Crate)",
    description: "Fresh grade-A tomatoes sourced weekly from Loitoktok smallholder farms. Best prices in Kitengela.",
    price: 1800, unit: "full crate (~30 kg)", category: "Fresh Produce", in_stock: true,
    image_url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-7", name: "Black Pepper 100g",
    description: "Whole black pepper corns. Sourced from coastal spice traders. Aromatic, fresh, and full-flavoured.",
    price: 120, unit: "100 g packet", category: "Spices", in_stock: true,
    image_url: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
  {
    id: "p-8", name: "Plastic Buckets (10L)",
    description: "Heavy-duty coloured plastic buckets. Sourced in bulk from Nairobi manufacturers. Ideal for home and business.",
    price: 250, unit: "per bucket", category: "Household", in_stock: false, badge: "Out of Stock",
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&w=400&q=75",
    whatsapp_order: "+254712345678",
  },
];

export const JOBS: Job[] = [
  {
    id: "job-1",
    title: "Retail Sales Associate",
    company: "Savanna Supermarket",
    town: "Kitengela",
    type: "Full-time",
    salary: "KSh 18,000 – 24,000 /month",
    description: "We are looking for a motivated sales associate to join our team at Savanna Supermarket. You will assist customers, manage shelves, and handle cash transactions.",
    requirements: ["KCSE Certificate or above", "Experience in retail is an advantage", "Honest and hardworking", "Good communication skills"],
    posted_days_ago: 2,
    whatsapp: "+254712345678",
    category: "Retail",
  },
  {
    id: "job-2",
    title: "Head Chef / Cook",
    company: "The Ochre Kitchen",
    town: "Kitengela",
    type: "Full-time",
    salary: "KSh 30,000 – 45,000 /month",
    description: "Experienced chef needed to lead our kitchen team. You will prepare authentic Kenyan dishes including Nyama Choma, pilau, and daily specials. Menu development role available for the right candidate.",
    requirements: ["Catering certificate from recognised institution", "3+ years kitchen experience", "Knowledge of Kenyan cuisine", "Ability to manage kitchen staff"],
    posted_days_ago: 5,
    whatsapp: "+254756789012",
    category: "Hospitality",
  },
  {
    id: "job-3",
    title: "Phone Technician",
    company: "Acacia Mobile Hub",
    town: "Kitengela",
    type: "Full-time",
    salary: "KSh 25,000 – 35,000 /month",
    description: "Skilled mobile phone technician needed to handle hardware and software repairs for all major brands. You will also assist customers with device setup and troubleshooting.",
    requirements: ["Diploma in Electronics or ICT", "2+ years phone repair experience", "Knowledge of Android and iOS", "Ability to work under pressure"],
    posted_days_ago: 1,
    whatsapp: "+254745678901",
    category: "Technology",
  },
  {
    id: "job-4",
    title: "Delivery & Logistics Driver",
    company: "Kajiado Directory",
    town: "Kitengela / Rongai",
    type: "Full-time",
    salary: "KSh 20,000 – 28,000 /month + fuel allowance",
    description: "Reliable driver needed to handle product deliveries across Kajiado County from our wholesale shop. You will pick up goods from suppliers and deliver to customers in Kitengela, Rongai, and surrounding areas.",
    requirements: ["Valid driving licence (Class BCE preferred)", "Clean driving record", "Knowledge of Kajiado County roads", "Own smartphone"],
    posted_days_ago: 3,
    whatsapp: "+254712345678",
    category: "Logistics",
  },
  {
    id: "job-5",
    title: "Pharmacy Sales Clerk",
    company: "Oloolua Pharmacy",
    town: "Rongai",
    type: "Full-time",
    salary: "KSh 22,000 – 28,000 /month",
    description: "A licensed pharmacy clerk is required to assist dispensing, customer service, and stock management. Must have a basic understanding of common medications and pharmacy operations.",
    requirements: ["Certificate in Pharmacy or related field", "Registered with Kenya Pharmacy Board (preferred)", "Good customer service skills", "Attention to detail"],
    posted_days_ago: 7,
    whatsapp: "+254778901234",
    category: "Health",
  },
  {
    id: "job-6",
    title: "Craft Workshop Trainer",
    company: "Maasai Craft Gallery",
    town: "Kitengela",
    type: "Part-time",
    salary: "KSh 1,500 – 2,000 /day",
    description: "Experienced Maasai beadwork artisan needed to run weekend craft workshops for visitors and school groups. Flexible hours — 2 to 3 days per week on weekends and holidays.",
    requirements: ["Proven beadwork and Maasai craft skills", "Good communication in English and Maa", "Experience teaching or training others", "Patient and creative"],
    posted_days_ago: 10,
    whatsapp: "+254723456789",
    category: "Arts & Culture",
  },
  {
    id: "job-7",
    title: "Hotel Receptionist",
    company: "Shepherd's Inn & Lounge",
    town: "Rongai",
    type: "Full-time",
    salary: "KSh 28,000 – 35,000 /month",
    description: "Professional receptionist needed to manage guest check-in/check-out, bookings, and front office operations. You will be the face of Shepherd's Inn.",
    requirements: ["Diploma in Hospitality or Front Office", "1+ year reception experience", "Excellent English communication", "Proficient in MS Office / booking software"],
    posted_days_ago: 4,
    whatsapp: "+254789012345",
    category: "Hospitality",
  },
];

export const JOB_CATEGORIES = ["All", "Retail", "Hospitality", "Technology", "Logistics", "Health", "Arts & Culture"];
export const JOB_TYPES = ["All", "Full-time", "Part-time", "Contract", "Casual"];

export const PRODUCT_CATEGORIES = ["All", "Dry Goods", "Oils & Fats", "Fresh Produce", "Household", "Crafts", "Spices"];
export const ALL_CATEGORIES = ["Grocery", "Crafts & Art", "Hardware", "Electronics", "Restaurant", "Health & Pharmacy", "Hospitality"];

export const CATEGORY_COLORS: Record<string, string> = {
  Grocery: "bg-acacia/10 text-acacia border-acacia/30",
  "Crafts & Art": "bg-ochre/10 text-ochre border-ochre/30",
  Hardware: "bg-gray-100 text-gray-600 border-gray-200",
  Electronics: "bg-blue-50 text-blue-600 border-blue-200",
  Restaurant: "bg-orange-50 text-orange-600 border-orange-200",
  "Health & Pharmacy": "bg-teal-50 text-teal-700 border-teal-200",
  Hospitality: "bg-purple-50 text-purple-600 border-purple-200",
};

export const CATEGORY_ACCENT: Record<string, string> = {
  Grocery: "#16a34a",
  "Crafts & Art": "#C36F48",
  Hardware: "#374151",
  Electronics: "#2563eb",
  Restaurant: "#ea580c",
  "Health & Pharmacy": "#0d9488",
  Hospitality: "#7c3aed",
};
